### ISSUE TITLE
Can we export http status code in our onSuccess and onError?

### ISSUE THREAD

**Issue by adonese** [tutipay/java-sdk#16]
We want to identify specific type of errors such as 401 ones so we can make a subsequent action

**Comment by adonese** [comment]
Related to <tutipay/app#175>

**Comment by rami3sam** [comment]
the last argument to the callback function ( both in the case of success and failure)  is of type ResponseData you can use the getCode method to get the Http status code ( i have implemented it yesterday)

**Comment by adonese** [comment]
Perfect, make sure to add documentations for the package since it will be used by other developers than us. From: rami3samSent: Monday, June 27, 2022 9:28 AMTo: tutipay/java-sdkCc: Mohamed Yousif; AuthorSubject: Re: [tutipay/java-sdk] Can we export http status code in our onSuccess and onError? (Issue #16) the last argument to the callback function ( both in the case of success and failure) is of type ResponseData you can use the getCode method to get the Http status code ( i have implemented it yesterday)—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>
