### ISSUE TITLE
billinquiry method performs a purchase instead

### ISSUE THREAD

**Issue by rami3sam** [tutipay/java-sdk#26]
i get invalid amount when calling TutiApiClient.billInquiry

**Comment by adonese** [comment]
Funny insight here, ebs has two endpoints:
- getBill
- payBill
AND at the same time, ebs also has two variants for payeeID for either (seriously?). Even if you send a request to `getBill` using a payeeID of a bill payment (not bill inquiry), the payeeID takes precedence over the endpoint and as a result we got that error.
